# Generated by Django 5.2.8 on 2025-12-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('autor', models.CharField(max_length=100)),
                ('url_noticia', models.URLField(max_length=300)),
                ('data_noticia', models.DateField()),
                ('fonte', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
            ],
        ),
    ]
